import Vue from "vue";
import {
  Button,
  Tabbar,
  TabbarItem,
  Field,
  Icon,
  CountDown,
  Collapse,
  CollapseItem,
  Overlay,
  Sidebar,
  SidebarItem,
  NavBar,
  SwipeCell,
  Card,
  Stepper,
  Checkbox,
  CheckboxGroup,
  Divider,
  Grid,
  GridItem,
  Form,
  Search,
  Tag,
} from "vant";

Vue.use(Button);
Vue.use(Tabbar);
Vue.use(TabbarItem);
Vue.use(Field);
Vue.use(Icon);
Vue.use(CountDown);
Vue.use(Collapse);
Vue.use(CollapseItem);
Vue.use(Overlay);
Vue.use(Sidebar);
Vue.use(SidebarItem);
Vue.use(NavBar);
Vue.use(SwipeCell);
Vue.use(Card);
Vue.use(Stepper);
Vue.use(Checkbox);
Vue.use(CheckboxGroup);
Vue.use(Divider);
Vue.use(Grid);
Vue.use(GridItem);
Vue.use(Form);
Vue.use(Search);
Vue.use(Tag);
